#!/usr/bin/env bash

set -e

export LC_ALL=C

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR="$SCRIPT_DIR/../.."

cd "$ROOT_DIR"

######################

echo "Check existence of GitHub actions workflow"

WORKFLOWS=$(find '.github/workflows/' -path '.github/workflows/classroom.yml' -prune -o -name '*.yml' -print)
echo "$WORKFLOWS"

[[ -n "$WORKFLOWS" ]] \
  || (echo "No workflow found except for classroom.yml" && exit 1)
